### ISSUE TITLE
nombre del juego

### ISSUE THREAD

**Issue by carolainnas** [Pyorg/P_2016#8]
chicos hay que ir pensando nombres para el juego, yo puse por poner algo intergalactika en la pantalla de inicio pero no es el definitivo, asi que nada, fijense y vamos tirando ideas

**Comment by madileweb** [comment]
Propongo los siguientes:
krone (corona)
starglow (como estrella brillante)
space trek (caminata espacial)

**Comment by carolainnas** [comment]
me gusta starglow :) 
si no intergalactika :P

**Comment by altope** [comment]
space trek

**Comment by carolainnas** [comment]
galaxy guard???

**Comment by WindarkRey** [comment]
Space Trek

**Comment by WindarkRey** [comment]
"Estrella brillante" no sería "Shining Star" ?

Galaxy Guard no esta mal... Incluso con ello podríamos utilizar el título, a su vez, como explicación de la historia...

"En un futuro remoto, gran cantidad de meteoritos se acercan a la tierra, tu deber será el de exterminarlos antes de que ellos acaben con nosotros....

confiamos en ti para esta misión..."

Héroe: La Nave.
Antagonista: los Meteoritos.

Algo como eso, que les parece? Creo es corto y conciso, y explica bien el juego...

Off-Topic: si, se que me desvíe un poco del tema principal, pero creo que no vendría mal este texto para explayar un poco el tema...

**Comment by carolainnas** [comment]
a mi me encanta :)

**Comment by carolainnas** [comment]
chicos, al final no se si queda galaxy guard o 
space battle confirmen!! para los doc

**Comment by altope** [comment]
como gusten...lo que está puesto hoy es Space Battle

2016-09-29 17:25 GMT-03:00 carolainnas notifications@github.com:

**Comment by diegozmweb** [comment]
Hasta donde se era Battle Space )?

**Comment by altope** [comment]
que pasa con Carballo el sábado ?

2016-09-29 23:08 GMT-03:00 Diego Madeo <notifications@github.com>:

**Comment by madileweb** [comment]
Battle Space
